---
- name: Enable and start docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_add_users_to_group

...
