---
- name: Enable and start docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add users to docker group
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_add_users_to_group

- name: Include Pip role
  ansible.builtin.include_role:
    name: diademiemi.python.pip
  vars:
    python_pip_global_packages: "{{ docker_pip_global_packages }}"
  when: docker_install_pip_package

...
