---
- name: Ensure apt dependencies are installed
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg
    state: present

- name: Add Docker APT repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] \
      https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['distribution_release'] | lower }} stable"
    state: present
    filename: docker

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

...
