---
_docker_pip_global_packages:
  - name: docker
    version: ">=2.0.0,<7.0.0"
  - name: docker-compose
  - name: PyYAML


_docker_arch_mapping:
  x86_64: amd64
  aarch64: arm64
  ppc64le: ppc64le
  s390x: s390x
  armv7l: arm

...
